### ISSUE TITLE
Add Tooltips

### ISSUE THREAD

**Issue by dcapra12** [ctriolo/settle#1]
Make things more understandable by having tooltips come up on hover.

**Comment by ctriolo** [comment]
http://twitter.github.com/bootstrap/javascript.html#tooltips

This will help us a lot with this issue.

**Comment by dcapra12** [comment]
That's awesome. The Popovers look really cool too.

**Comment by ctriolo** [comment]
You are going to have to link to the js from the html/jade, its over in `public/bootstrap/js` so its path will just be `bootstrap/js/filename.js` once it is up and running on the server.

**Comment by dcapra12** [comment]
This is done for building. Could still do more with it. Maybe add tooltip to cards to tell which one it is?

**Comment by ctriolo** [comment]
def. tooltips everywhere im thinking...

**Comment by dcapra12** [comment]
done. 9dac9babe83424a217c4476e15b2e99cbb1854dd. we need more people to play our game to let us know what else isn't obvious.
