### ISSUE TITLE
create cheats for demo

### ISSUE THREAD

**Issue by dcapra12** [ctriolo/settle#103]
'b' for brick, 'o' for ore, 's' for sheep, 'w' for wheat, 'l' for lumber, 'v' for victory points

**Comment by ctriolo** [comment]
ed5e69a37cf4bf3062cc47703641ec1c72f90ba0

You may need to hold `SHIFT` to get these.

`b`, `l`, `o`, `s`, `w` for resources
`k`, `r`, `y`, `m` for developments
`v` for victory points
