### ISSUE TITLE
Card visuals

### ISSUE THREAD

**Issue by dcapra12** [ctriolo/settle#16]
Group similar cards together in card well (all sheep with each other, all wheat with each other). Handle overrun if too many cards by either scaling down size or allowing second row.

**Comment by ctriolo** [comment]
I think you could do the grouping by just having lists within the list. **I N C E P T I O N**.

``` html
<ul class="resource-cards">
  <li><ul class="sheep-cards"></ul></li>
  <li><ul class="wood-cards"></ul></li>
  ...
</ul>
```

And then you can fix up the css so you can just append an `<li><div /></li>` to the correct sublist when you want to add a card of sublist type.

**Comment by dcapra12** [comment]
yeap that should definitely work.

**Comment by ctriolo** [comment]
e5c154b6b47c50e4355475ad1a458bd45cfb1345 fixed another way
