### ISSUE TITLE
Highlight whose turn it is.

### ISSUE THREAD

**Issue by dcapra12** [ctriolo/settle#18]
Either by making name tag a different color, changing border color of player well etc.

**Comment by dcapra12** [comment]
This also includes graying out and deactivating roll, build, trade and stop cards unless it is your turn.

**Comment by ctriolo** [comment]
85b0fda57549981a542854c18fbdca56f87eac60 by @dcapra12

**Comment by dcapra12** [comment]
done and done. 768b988e30
