### ISSUE TITLE
Facebook Auth

### ISSUE THREAD

**Issue by dcapra12** [ctriolo/settle#30]
Get Facebook Auth working, and begin displaying Facebook profile pictures and names where possible.

**Comment by ctriolo** [comment]
This [stackoverflow question](http://stackoverflow.com/questions/5765063/node-js-connect-auth-vs-everyauth) will be useful. Make sure to look at the second best question where the author of everyauth explains their case.

**Comment by dcapra12** [comment]
Yeah good find. This looks solid http://documentup.com/bnoguchi/everyauth/ I'll get on this tomorrow, and hopefully have Facebook Profile Pics up. -- how will this work on localhost?

**Comment by ctriolo** [comment]
I don't understand your question. Do you mean how do we test? Because we each will only have our own facebook account to login with?

[Facebook API: Test Users](https://developers.facebook.com/docs/test_users/)

**Comment by dcapra12** [comment]
yeap exactly what I was asking.

**Comment by dcapra12** [comment]
closing. nice job Chris!
