### ISSUE TITLE
figure out behavior for exiting/re-entering game

### ISSUE THREAD

**Issue by dcapra12** [ctriolo/settle#67]
What happens when player leaves? Does the whole game end and all players get sent back to dashboard?

If not, should we allow player to get back into the game within say a minute? If this, then we need to redraw the board for the reentering player.

**Comment by ctriolo** [comment]
it might be easiest just to kill the player. he cannot rejoin, and his pieces stay on the board, his turns are skipped.

**Comment by RafiRome** [comment]
If we do what Chris said, we could tie it into a forfeit option.

**Comment by ctriolo** [comment]
THIS IS DONE. I DON'T BELIEVE IT.
