### ISSUE TITLE
don't allow players to join a game that has already started

### ISSUE THREAD

**Issue by dcapra12** [ctriolo/settle#72]
maybe disable the game on dashboard

**Comment by ctriolo** [comment]
yeup, games that are started are not on the dashboard, =D. my thinking was
that, only joinable games should show up on the dashboard. i guess, the
question is, is this how it should be?

On Fri, May 4, 2012 at 11:58 AM, dcapra12 <
reply@reply.github.com

**Comment by dcapra12** [comment]
one step ahead haha! might be nice to see which games are currently in session ( or at least have the possibility to), to show how many users we have on?

**Comment by ctriolo** [comment]
non-issue bro
