### ISSUE TITLE
Add more spacing to the end game dialog.

### ISSUE THREAD

**Issue by elancast** [ctriolo/settle#77]
HERE:
![This is alt](http://i.imgur.com/bhJyN.png)

Please please please add spacing. :'( I'm guessing this is an easy fix.

**Comment by ctriolo** [comment]
Thanks! Give us more issues! =D

**Comment by elancast** [comment]
ok!

**Comment by dcapra12** [comment]
yeap, as said earlier, the gameover screen looks awful, and should probably have more than just spacing. I'll get to it! Thanks for the issues, always good to hear from a new set of eyes!

**Comment by dcapra12** [comment]
f552df69560af4f8953e5d7245e8c86514fee28c. still would prefer the winner's facebook profile picture to show up or something
