### ISSUE TITLE
BUG: clicked to buy a dev card, nothing happens

### ISSUE THREAD

**Issue by RafiRome** [ctriolo/settle#85]
I had 1 wheat, 3 sheep, 1 stone. Clicked to buy a dev card, nothing happened. I gained no dev card and I lost no resources. Only thing that happened is the dev card buy option got disabled so I could buy no dev card. Next turn, same problem.

**Comment by dcapra12** [comment]
fixed. forgot to remove a couple lines in a previous push. 948fe169097e85669430fd0f9b1277f9087414ad
